[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"
watchPaths = ["frontend"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 80
health_check_path = "/" 